sonar.projectKey=agent-service
sonar.organization=huzaifa678
sonar.projectName=agent-service
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8
sonar.java.source=21

sonar.sources=agent-service/agent-domain/src/main/java,\
  agent-service/agent-application/src/main/java,\
  agent-service/agent-adapter/src/main/java,\
  agent-service/agent-bootstrap/src/main/java
sonar.tests=agent-service/agent-domain/src/test/java,\
  agent-service/agent-application/src/test/java,\
  agent-service/agent-adapter/src/test/java,\
  agent-service/agent-bootstrap/src/test/java

sonar.java.binaries=agent-service/**/build/classes/java/main
sonar.java.test.binaries=agent-service/**/build/classes/java/test

sonar.coverage.jacoco.xmlReportPaths=agent-service/**/build/reports/jacoco/**/*.xml
sonar.junit.reportPaths=agent-service/**/build/test-results/test

sonar.exclusions=**/build/**,**/generated/**
sonar.coverage.exclusions=**/*Application.java,**/config/**,**/dto/**
